spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/github_analyzer}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.postgresql.Driver}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        dialect: ${SPRING_JPA_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
  logging:
    level:
      org.hibernate: ERROR
      org.hibernate.SQL: OFF
      org.hibernate.type.descriptor.sql: OFF

  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}
    baseline-on-migrate: true
    baseline-version: 0
    table: flyway_schema_history
    validate-on-migrate: true
    clean-disabled: true
    patterns: ${FLYWAY_PATTERNS:V*__*.sql}

github:
  api:
    base-url: ${GITHUB_BASE_URL:https://api.github.com}
    token: ${GITHUB_TOKEN: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}
    rate-limit:
      # Default rate limit (requests per hour)
      default-limit: 5000
      # Default window duration in seconds
      default-window-seconds: 3600
      # Buffer percentage to keep available
      buffer-percentage: 1

# Swagger UI custom path
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: alpha
    enabled: true
  api-docs:
    path: /api-docs 

app:
  scheduler:
    fixed-rate: ${SCHEDULER_RATE:300000}  # 5 minutes in milliseconds

logging:
  level:
    com.toulios.githubanalyzer: DEBUG 

resilience4j:
  ratelimiter:
    instances:
      observedRepoApi:
        limitForPeriod: ${RATE_LIMIT_PER_PERIOD:100}
        limitRefreshPeriod: ${RATE_LIMIT_PERIOD:1m}
        timeoutDuration: ${RATE_LIMIT_TIMEOUT_DURATION:0}